import { problem1 }  from "./problem_1";
import { problem2 }  from "./problem_2";
import { problem3 }  from "./problem_3";
import { problem4 }  from "./problem_4";
import { problem5 }  from "./problem_5";
import { problem6 }  from "./problem_6";
import { problem7 }  from "./problem_7";
import { problem8 }  from "./problem_8";
import { problem9 }  from "./problem_9";
import { problem10 } from "./problem_10";
import { problem11 } from "./problem_11";
import { problem12 } from "./problem_12";
import { problem13 } from "./problem_13";
import { problem14 } from "./problem_14";
import { problem15 } from "./problem_15";
import { problem16 } from "./problem_16";
import { problem17 } from "./problem_17";
import { problem18 } from "./problem_18";
import { problem19 } from "./problem_19";
import { problem20 } from "./problem_20";
import { problem21 } from "./problem_21";
import { problem22 } from "./problem_22";
import { problem23 } from "./problem_23";
import { problem24 } from "./problem_24";
import { problem25 } from "./problem_25";
import { problem26 } from "./problem_26";
import { problem27 } from "./problem_27";
import { problem28 } from "./problem_28";
import { problem29 } from "./problem_29";
import { problem30 } from "./problem_30";
import { problem31 } from "./problem_31";
import { problem32 } from "./problem_32";
import { problem33 } from "./problem_33";
import { problem34 } from "./problem_34";
import { problem35 } from "./problem_35";
import { problem36 } from "./problem_36";
import { problem37 } from "./problem_37";
import { problem38 } from "./problem_38";
import { problem39 } from "./problem_39";
import { problem40 } from "./problem_40";
import { problem41 } from "./problem_41";
import { problem42 } from "./problem_42";
import { problem43 } from "./problem_43";

problem1();
problem2();
problem3();
problem4();
problem5();
problem6();
problem7();
problem8();
problem9();
await problem10();
problem11();
problem12();
problem13();
problem14();
problem15();
problem16();
problem17();
problem18();
problem19();
problem20();
problem21();
problem22();
problem23();
problem24();
problem25();
problem26();
problem27();
problem28();
problem29();
problem30();
problem31();
problem32();
problem33();
problem34();
problem35();
problem36();
problem37();
problem38();
problem39();
problem40();
problem41();
problem42();
problem43();
