import { problem1 }  from "./problem_1";
import { problem2 }  from "./problem_2";
import { problem3 }  from "./problem_3";
import { problem4 }  from "./problem_4";
import { problem5 }  from "./problem_5";
import { problem6 }  from "./problem_6";
import { problem7 }  from "./problem_7";
import { problem8 }  from "./problem_8";
import { problem9 }  from "./problem_9";
import { problem10 } from "./problem_10";
import { problem11 } from "./problem_11";
import { problem12 } from "./problem_12";
import { problem13 } from "./problem_13";
import { problem14 } from "./problem_14";
import { problem15 } from "./problem_15";
import { problem16 } from "./problem_16";
import { problem17 } from "./problem_17";
import { problem18 } from "./problem_18";
import { problem19 } from "./problem_19";
import { problem20 } from "./problem_20";
import { problem21 } from "./problem_21";
import { problem22 } from "./problem_22";
import { problem23 } from "./problem_23";

problem1();
problem2();
problem3();
problem4();
problem5();
problem6();
problem7();
problem8();
problem9();
await problem10();
problem11();
problem12();
problem13();
problem14();
problem15();
problem16();
problem17();
problem18();
problem19();
problem20();
problem21();
problem22();
problem23();
